[package]
name = "textsub-server"
version = "1.0.0"
edition = "2021"
authors = ["doublecouponday <mail@samueljenks.me>", "bobscorn <qwertster0@gmail.com>" ]

[dependencies]
rocket = "=0.5.0-rc.3"


[[bin]]
name = "textsub-server"
path = "server.rs"
